spring.application.name=demo
# Cofiguracion de la base de datos
spring.datasource.url=jdbc:h2:mem:yogurt;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuracion de JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initializacion=true

#Configuracion de H2 y su consola
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Ajustes para el logging de hibernate
logging.level.com.yogurtmaking=DEBUG
logging.level.org.hibernate.sql=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Puerto de nuestra app
server.port=8082

# Inicializacion de sql
spring.sql.init.mode=always
spring.sql.init.data-locations

# Swagger UI base path compatible con Springdoc 2
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
